language: node
cache:
- node_modules

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://test-sarab-projectmanagement.herokuapp.com
  only:
  - master

  # before_script:
  provider: heroku
  api_key:
    secure: KEY
  app: test-sarab-projectmanagement
  on:
    repo: sarabs3/task-management

